POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
   "username":"大和iiiiiii",
   "password":"22288fff",
   "confirmPassword":"22288fff"
}

###
POST http://localhost:8000/api/v1/ligin
Content-Type: application/json

{
   "username":"大和きちffff",
   "password":"22288fff",
   "confirmPassword":"22288fff"
}
